### ISSUE TITLE
插件 ChatGPT 抛出错误: onMounted 发生错误: {}

### ISSUE THREAD

**Issue by rookie2onion** [KiviBotLab/kivibot-plugin-chatgpt#3]
你好：
在启动插件时弹出错误，如下：
`[16:46:22-QQ号] - {
  "name": "KiviPluginError",
  "pluginName": "ChatGPT",
  "message": "onMounted 发生错误: \n{}"
}`

系统版本是windows 25262.1000

不常提交issue，如果有任何需要补充提交的信息，我会尽快补上

感谢！

**Comment by vikiboss** [comment]
这应该和上一个 issue 类似，由于近期 ChatGPT 的流量太大，加了多重验证导致上层的接口失效而验证出错，正在等待解决方案。

**Comment by rookie2onion** [comment]
> 这应该和上一个 issue 类似，由于近期 ChatGPT 的流量太大，加了多重验证导致上层的接口失效而验证出错，正在等待解决方案。

嗷，辛苦了！感谢回复

**Comment by vikiboss** [comment]
已迁移到官方 OpenAI 模块进行调用，请更新到最新版本
