### ISSUE TITLE
新的可能性

### ISSUE THREAD

**Issue by GinirohikoCha** [KiviBotLab/kivibot-plugin-chatgpt#4]
目前通过axios直接http请求加上openAI账户提供的apikey完成了请求访问 并且无其他依赖限制
![image](https://user-images.githubusercontent.com/26181775/207493424-0a92ce8a-8fba-4c8c-b891-2662b1e051e7.png)

但是目前没有查找到chatgpt-api中包含的conversationId的支持，猜测可以通过将传来的数据与之前的文本进行拼接作为参数再传递会达到同样的结果，该模型或许应该用completion角度理解更合适。

可能需要些时间查看chatgpt-api源码以提供pr或者搓新的轮子

**Comment by vikiboss** [comment]
已迁移到官方 OpenAI 模块进行调用
