### ISSUE TITLE
chatgpt-api和openai的区别是什么？

### ISSUE THREAD

**Issue by zangguojun** [KiviBotLab/kivibot-plugin-chatgpt#6]
我发现你在v2版本将非官方的chatgpt-api更换为openai，我从chatgpt-api的仓库过来，也了解了chatgpt在上一个版本更新后引入了cloudflare防护，导致chatgpt-api不得不使用较重的puppeteer的方式。
我比较纳闷的是，openai已经是3.x版本了，说明在此前都有这个包，为什么当初选择比较重的chatgpt-api？
或者说chatgpt-api相比openai有什么优势？
> 另外想询问一下，chatgpt是openai的哪一个模型？我看你在v2的版本里面替换chatgpt为text-davinci-003？chatgpt和text-davinci-003是完全相同吗？我觉得应该不是吧？

**Comment by vikiboss** [comment]
- `chatgpt-api` 是社区的 npm 模块。
- `openai` 是 OpenAI 官方发布的 npm 模块。
- `chatgpt-api` 在早期版本是利用 OpenAI 开放的[网页项目](https://chat.openai.com/chat)的 Cookie 实现 AI 聊天，并且早期并无其他限制（额度，到期时间等），无需申请 `apikey`，相对方便，但是现在这个在线的项目加了诸多限制，如果继续用社区模块调用相当困难，而且要求比较苛刻。
- 考虑之后，迁移到了 `openai` 官方模块，进行调用，虽然要申请 `apikey`，但是相比 `puppeteer` 无疑要方便的多，而且都是直接调用官方维护和开发的 API，在效率、稳定性等方面都要好。
- kivibot-plugin-chatgpt 并无所谓 v2 版本，一直都是 v1，但确实有 [fork 的 v2 版本](https://github.com/GinirohikoCha/kivibot-plugin-chatgptv2/blob/master/package.json#L4)，他尝试继续使用 `chatgpt-api` 社区模块进行调用。
- 至于模型，不太清楚，`chatgpt-api` 使用的网页项目的模型似乎比较老，不够聪明，这一点也是官方模块的优势。
- 至于为什么使用 `text-davinci-003` 模型，主要因为他的定位是 `chat`，比较综合，适合大多数场景，能写代码，也能应付其他问答场景。
- 关于模型的区别，你可以参考 OpenAI 的[官方文档](https://beta.openai.com/docs/models/gpt-3)了解更多

**Comment by zangguojun** [comment]
好的 感谢解答！
